<a href="https://colab.research.google.com/github/AdityaSVNIT2028/pytorch/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
import numpy as np

In [22]:
# in this we look around the math operations in this
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [23]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [24]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
#substraact
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [26]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [27]:
# multiplication
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [28]:
#division
tensor_b/ tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [29]:
torch.div(tensor_b, tensor_b)

tensor([1., 1., 1., 1.])

In [30]:
# now the remainder
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [31]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [32]:
# for exponent and power
tensor_a**tensor_b

tensor([    1,    64,  2187, 65536])

In [33]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [34]:
print(tensor_a)
tensor_a.add (tensor_b)
print(tensor_a)

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])


In [35]:
# here one important thing to note that if we are usign
# tensor_a.add() and tensor_a.add_() then by 2nd we directly
# reassign
tensor_a.add_(tensor_b)
print(tensor_a )

tensor([ 6,  8, 10, 12])
